"use strict";
const pool=require('../db');
const {logAudit}=require('../utils/audit');
const bid=req=>Number(req.businessId||req.user?.businessId);
const METHODS=new Set(['cash','mobile_money','bank','other']);
function parse(body={}){return {category:String(body.category||'').trim().slice(0,100),description:String(body.description||'').trim().slice(0,255),amount:Number(body.amount),paymentMethod:String(body.paymentMethod||'cash'),reference:String(body.reference||'').trim().slice(0,120)||null,expenseDate:body.expenseDate||null};}
function validate(d){if(!d.category||!d.description||!(d.amount>0)||!Number.isFinite(d.amount)||!METHODS.has(d.paymentMethod))return 'Category, description, valid amount and payment method are required.';if(d.expenseDate&&!/^\d{4}-\d{2}-\d{2}$/.test(String(d.expenseDate)))return 'Invalid expense date.';return null;}
async function listExpenses(req,res){const b=bid(req);const days=Math.min(Math.max(Number(req.query.days)||30,1),365);try{const r=await pool.query(`SELECT e.*,u.name created_by_name FROM expenses e LEFT JOIN users u ON u.id=e.created_by AND u.business_id=e.business_id WHERE e.business_id=$1 AND e.expense_date>=CURRENT_DATE-($2::int-1) ORDER BY e.expense_date DESC,e.id DESC`,[b,days]);res.json({expenses:r.rows,total:r.rows.reduce((a,x)=>a+Number(x.amount),0),days})}catch(e){console.error('LIST EXPENSES ERROR',e);res.status(500).json({message:'Failed to load expenses.'})}}
async function createExpense(req,res){const b=bid(req),d=parse(req.body);const error=validate(d);if(error)return res.status(400).json({message:error});try{const r=await pool.query(`INSERT INTO expenses(business_id,branch_id,category,description,amount,payment_method,reference,expense_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8::date,CURRENT_DATE),$9) RETURNING *`,[b,req.branchId,d.category,d.description,d.amount,d.paymentMethod,d.reference,d.expenseDate,req.user.id]);await logAudit(req,'expense.created','expense',r.rows[0].id,{amount:d.amount,category:d.category});res.status(201).json({message:'Expense recorded successfully.',expense:r.rows[0]})}catch(e){console.error('CREATE EXPENSE ERROR',e);res.status(500).json({message:'Failed to record expense.'})}}
async function updateExpense(req,res){const b=bid(req),id=Number(req.params.id),d=parse(req.body);if(!Number.isInteger(id)||id<=0)return res.status(400).json({message:'Invalid expense.'});const error=validate(d);if(error)return res.status(400).json({message:error});try{const r=await pool.query(`UPDATE expenses SET category=$1,description=$2,amount=$3,payment_method=$4,reference=$5,expense_date=COALESCE($6::date,expense_date),updated_at=NOW() WHERE id=$7 AND business_id=$8 RETURNING *`,[d.category,d.description,d.amount,d.paymentMethod,d.reference,d.expenseDate,id,b]);if(!r.rowCount)return res.status(404).json({message:'Expense not found.'});await logAudit(req,'expense.updated','expense',id,{amount:d.amount,category:d.category});res.json({message:'Expense updated successfully.',expense:r.rows[0]})}catch(e){console.error('UPDATE EXPENSE ERROR',e);res.status(500).json({message:'Failed to update expense.'})}}
async function deleteExpense(req,res){try{const r=await pool.query(`DELETE FROM expenses WHERE id=$1 AND business_id=$2 RETURNING id,amount,category`,[Number(req.params.id),bid(req)]);if(!r.rowCount)return res.status(404).json({message:'Expense not found.'});await logAudit(req,'expense.deleted','expense',r.rows[0].id,r.rows[0]);res.json({message:'Expense deleted.',expense:r.rows[0]})}catch(e){console.error('DELETE EXPENSE ERROR',e);res.status(500).json({message:'Failed to delete expense.'})}}
module.exports={listExpenses,createExpense,updateExpense,deleteExpense};
