 "use strict";
const express=require("express");
const {requireAuth,authorizeRoles}=require("../middleware/authMiddleware");
const c=require("../controllers/whatsappController");
const r=express.Router();
r.get("/webhook",c.webhookVerify);
r.post("/webhook",c.webhook);
r.get("/settings",requireAuth,c.settings);
r.post("/settings",requireAuth,authorizeRoles("owner","manager"),c.saveSettings);
r.post("/connect/start",requireAuth,authorizeRoles("owner","manager"),c.startConnection);
r.post("/connect",requireAuth,authorizeRoles("owner","manager"),c.connect);
r.post("/connection/test",requireAuth,authorizeRoles("owner","manager"),c.testConnection);
r.delete("/connection",requireAuth,authorizeRoles("owner","manager"),c.disconnect);
r.post("/agent/toggle",requireAuth,authorizeRoles("owner","manager"),c.toggleAgent);
r.get("/analytics",requireAuth,c.analytics);
r.get("/conversations",requireAuth,c.conversations);
r.get("/conversations/:id/messages",requireAuth,c.messages);
r.post("/conversations/:id/takeover",requireAuth,authorizeRoles("owner","manager","cashier"),c.takeover);
r.post("/conversations/:id/reply",requireAuth,authorizeRoles("owner","manager","cashier"),c.sendHuman);
module.exports=r;
