"use strict";
let sales=[],currentSale=null;
const money=v=>`TSh ${Number(v||0).toLocaleString("en-TZ",{maximumFractionDigits:2})}`;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
async function json(url,o={}){const r=await fetch(url,{credentials:"include",...o,headers:{Accept:"application/json",...(o.body?{"Content-Type":"application/json"}:{}),...(o.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.message||"Request failed.");return x;}
async function loadSales(){const x=await json("/api/sales");sales=x.sales||[];document.querySelector("#return-sale").innerHTML=`<option value="">Select sale</option>`+sales.map(s=>`<option value="${s.id}">${esc(s.receipt_number)} — ${money(s.total_amount)}</option>`).join("");}
async function loadReturns(){const x=await json("/api/returns");document.querySelector("#returns-body").innerHTML=(x.returns||[]).length?x.returns.map(r=>`<tr><td>${esc(r.return_number)}</td><td>${esc(r.receipt_number)}</td><td>${esc(r.customer_name||"Walk-in")}</td><td>${money(r.total_amount)}</td><td>${esc(r.refund_method)}</td><td>${new Date(r.created_at).toLocaleDateString("en-GB")}</td></tr>`).join(""):`<tr><td colspan="6">No returns yet.</td></tr>`;}
async function selectSale(id){if(!id){currentSale=null;document.querySelector("#return-items tbody").innerHTML=`<tr><td colspan="4">Select a sale.</td></tr>`;return;}currentSale=(await json(`/api/sales/${id}`));const body=document.querySelector("#return-items tbody");body.innerHTML=(currentSale.items||[]).map(i=>`<tr><td><strong>${esc(i.product_name)}</strong></td><td>${i.quantity}</td><td><input class="return-qty" data-item="${i.id}" data-price="${i.unit_price}" type="number" min="0" max="${i.quantity}" step="1" value="0"></td><td data-amount="${i.id}">${money(0)}</td></tr>`).join("")||`<tr><td colspan="4">No items found.</td></tr>`;document.querySelectorAll(".return-qty").forEach(inp=>inp.addEventListener("input",()=>{document.querySelector(`[data-amount="${inp.dataset.item}"]`).textContent=money(Number(inp.value)*Number(inp.dataset.price));}));}
document.addEventListener("DOMContentLoaded",async()=>{try{await Promise.all([loadSales(),loadReturns()]);}catch(e){document.querySelector("#return-message").textContent=e.message;}document.querySelector("#return-sale").addEventListener("change",e=>selectSale(e.target.value));document.querySelector("#return-submit").addEventListener("click",async()=>{const b=document.querySelector("#return-submit"),m=document.querySelector("#return-message");if(!currentSale)return m.textContent="Select a sale first.";const items=[...document.querySelectorAll(".return-qty")].map(x=>({saleItemId:Number(x.dataset.item),quantity:Number(x.value)})).filter(x=>x.quantity>0);if(!items.length)return m.textContent="Enter at least one return quantity.";b.disabled=true;b.textContent="Processing...";try{await json("/api/returns",{method:"POST",body:JSON.stringify({saleId:currentSale.sale.id,items,refundMethod:document.querySelector("#return-method").value,refundReference:document.querySelector("#return-reference").value,reason:document.querySelector("#return-reason").value})});m.textContent="Return completed successfully.";m.className="form-message success";await loadSales();await loadReturns();document.querySelector("#return-sale").value="";await selectSale("");}catch(e){m.textContent=e.message;m.className="form-message error";}finally{b.disabled=false;b.textContent="Complete Return";}});});
